### ISSUE TITLE
Clarification -regd

### ISSUE THREAD

**Issue by balajijana** [MrPardeep/Angular2-DatePicker#2]
I need to know whether we can use this module without using boot-flat theme. Will it support for the other theme as well?

**Comment by PardeepJain** [comment]
answer is simply yes,

Yes we can use this datepicker without using this module named as BOOTFLAT, actually bootflat has nothing to do with this datepicker except design. I have used (bootflat) to give some interactive design to this datepicker. if you don't want to use this theme for your use case just put you own css/Scss whatever you want, than you dont need to install this package (bootflat).

**Comment by erpardeepjain** [comment]
Answer is simply yes,

Yes we can use this datepicker without using this module named as BOOTFLAT, actually bootflat has nothing to do with this datepicker except design. I have used (bootflat) to give some interactive design to this datepicker. if you don't want to use this theme for your use case just put you own css/Scss whatever you want, than you dont need to install this package (bootflat).
