### ISSUE TITLE
Any NPM Package

### ISSUE THREAD

**Issue by balajijana** [MrPardeep/Angular2-DatePicker#3]
Hi,

 Do we have this module as npm package? how can we install using npm install

**Comment by PardeepJain** [comment]
hello @balajijana , 

Yes we can install this package as npm bundle , you just need to run this command in your terminal i.e * npm install bootflat --save 
also we can install bootflat as bower dependency by running this command

*  bower install bootflat --save

see here for more information https://www.npmjs.com/package/bootflat , 

Hope you got clear with this.

**Comment by erpardeepjain** [comment]
hello @balajijana ,

Yes we can install this package as npm bundle , you just need to run this command in your terminal i.e \* npm install bootflat --save 
also we can install bootflat as bower dependency by running this command

bower install bootflat --save
see here for more information https://www.npmjs.com/package/bootflat ,

Hope you got clear with this.
